### ISSUE TITLE
It would be nice to be able to adjust the width

### ISSUE THREAD

**Issue by zhl111** [brunolemos/simplified-twitter#19]
Now it's a bit narrow

**Comment by HolmesMalone** [comment]
I agree,

**Comment by xatier** [comment]
I've patched the stylesheet as following. As mentioned in the README, we probably shouldn't mess with the CSS, the patch can be fragile and may break when they update their client code.


```css
diff --git a/chrome/styles.css b/chrome/styles.css
index 58304c2..21b37d2 100644
--- a/chrome/styles.css
+++ b/chrome/styles.css
@@ -8,3 +8,16 @@ @media (min-width: 800px) {
     max-width: 500px !important;
   }
 }
+
+[role='main'] > div {
+  width: 1000px !important;
+}
+
+div[data-testid='primaryColumn'] {
+  width: 1000px !important;
+  max-width: 1000px !important;
+}
+
+div[data-testid='primaryColumn'] > div > div:nth-child(5) {
+  max-width: 1000px;
+}
```

**Comment by xatier** [comment]
Wow, can't believe it's already 2026!

For those who seek for adjusting the width, the following stylesheet should do the trick.
This is overriding the dictating class `.r-1ye8kvj`, which might get a name change if twitter recompiler their frontend.

```css
#react-root main {
  -webkit-flex-grow: 1 !important;
  flex-grow: 1 !important;
}

@media (min-width: 800px) {
  [role='listbox'] {
    max-width: 500px !important;
  }
}

[role='main'] > div {
  width: 1000px !important;
}

/* remove the constraint .r-1ye8kvj{max-width:600px;} */
.r-1ye8kvj {
    max-width: 1000px !important;
}
```
